id: P008159
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4037
  title: དཔལ་ལྡན་ས་སྐྱ་པའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    853100b8388d4d61889d9c9666c65a4e:
      image_group_id: I3CN4223
      title: ''
      volume_number: 1
      total_pages: 938
ebook_metadata:
  title: དཔལ་ལྡན་ས་སྐྱ་པའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P008159
  cover: cover.jpg
  layers:
  - pagination
